'use client';

import { useState } from 'react';
import Link from 'next/link';
import { 
  HelpCircle, 
  ChevronDown, 
  ChevronUp, 
  Search, 
  Mail,
  Layers,
  ShieldAlert,
  Eye,
  Lock,
  Scale,
  LayoutGrid
} from 'lucide-react';

import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';

interface FAQItem {
  id: string;
  category: string;
  question: string;
  answer: string;
}

const FAQ_DATA: FAQItem[] = [
  // Detection Scope
  {
    id: '1',
    category: 'Detection Scope',
    question: 'Which AI image generators does SignalScope support?',
    answer: 'SignalScope is designed for Zero-Shot Generalization across unseen generators. It accurately classifies images from FLUX.1, Midjourney v6, Stable Diffusion XL (SDXL), DALL-E 3, Imagen 3, Firefly, VQ-GAN, and StyleGAN 3 without needing model-specific re-training.'
  },
  {
    id: '2',
    category: 'Detection Scope',
    question: 'How does SignalScope perform zero-shot detection on new, unreleased AI models?',
    answer: 'Instead of memorizing generator-specific artifacts, Stream A leverages frozen DINOv2 / CLIP ViT-L/14 semantic representations, while Stream B evaluates universal physical invariants (sensor PRNU noise variance, Bayer cross-channel correlation, and 2D spatial Fourier spectra) that diffusion algorithms inherently lack.'
  },
  // False Positive Defense
  {
    id: '3',
    category: 'False Positive Defense',
    question: 'Will photos taken on iPhones or Google Pixel phones trigger false positive AI verdicts?',
    answer: 'No. Modern smartphones rely heavily on computational photography (Apple Photonic Engine, Google Pixel HDR+). SignalScope includes a Bayer Cross-Channel Noise Correlation Gate (rho_R,G > 0.60). Real CMOS sensors exhibit strong inter-channel noise coupling, which prevents computational HDR photos from being flagged as synthetic.'
  },
  {
    id: '4',
    category: 'False Positive Defense',
    question: 'How does SignalScope handle social media re-compression (WhatsApp, Instagram, Twitter)?',
    answer: 'Social media platforms apply heavy JPEG compression. SignalScope integrates a JPEG 8x8 DCT Notch Filter within its 2D CUDA Fast Fourier Transform (FFT) spectrum, masking fundamental compression block boundary harmonics to prevent false positive AI spectral spikes.'
  },
  // Explainability & Heatmaps
  {
    id: '5',
    category: 'Explainability & Heatmaps',
    question: 'How are the LayerNorm Bipolar spatial heatmaps generated?',
    answer: 'Patch attributions are computed by backpropagating ViT patch activations through frozen LayerNorm representations and applying zero-point anchored scaling (S_p in [-1.0, +1.0]). Positive values (S_p > +0.15) highlight synthetic AI anomalies in red/yellow, while negative values (S_p < -0.15) highlight authentic optical camera evidence in cyan.'
  },
  {
    id: '6',
    category: 'Explainability & Heatmaps',
    question: 'Are the structured evidence cards generated by an LLM that might hallucinate?',
    answer: 'No. Every evidence string rendered by SignalScope is served deterministically from exact physical signal extractors (sanitizer, spectral, texture, ela, metadata). There are zero Large Language Models involved, eliminating hallucinations entirely.'
  },
  // Privacy & Security
  {
    id: '7',
    category: 'Privacy & Security',
    question: 'Are uploaded images saved, stored, or used for training?',
    answer: 'No. SignalScope operates under a strict Zero-Retention Privacy Policy. Images sent to the /predict API are ingested in-memory via Python BytesIO streams, analyzed in real-time, and immediately garbage-collected. No images are saved to disk or logged.'
  },
  {
    id: '8',
    category: 'Privacy & Security',
    question: 'Is the image analysis processed server-side or on my device?',
    answer: 'Analysis is performed server-side within a sandboxed inference container. The pipeline uses ephemeral memory buffers throughout. No persistent filesystem writes occur at any stage — images are processed in a completely stateless request lifecycle.'
  },
  // Legal & Ethics
  {
    id: '9',
    category: 'Legal & Ethics',
    question: 'Can a SignalScope verdict be presented as absolute legal proof in court?',
    answer: 'SignalScope provides a scientific, calibrated statistical probability index based on multi-vector spatial and frequency domain signals. In accordance with forensic ethics, verdicts are framed as "likely AI-generated" or "likely real" as estimation tools, not definitive legal proof.'
  },
  {
    id: '10',
    category: 'Legal & Ethics',
    question: 'Is it ethical to use SignalScope to audit images without the subject\'s knowledge?',
    answer: 'SignalScope is designed as a forensic verification tool for journalism, academia, and security research. Users are solely responsible for compliance with applicable privacy laws and ethical norms in their jurisdiction. The tool outputs probability estimates, not punitive conclusions.'
  },
];

const CATEGORY_CONFIG = [
  { key: 'All',                      label: 'All',                      Icon: LayoutGrid  },
  { key: 'Detection Scope',          label: 'Detection Scope',          Icon: Layers      },
  { key: 'False Positive Defense',   label: 'False+ Defense',           Icon: ShieldAlert },
  { key: 'Explainability & Heatmaps',label: 'Explainability',           Icon: Eye         },
  { key: 'Privacy & Security',       label: 'Privacy & Security',       Icon: Lock        },
  { key: 'Legal & Ethics',           label: 'Legal & Ethics',           Icon: Scale       },
];

export default function FAQPage() {
  const [searchTerm, setSearchTerm]         = useState('');
  const [openIds, setOpenIds]               = useState<string[]>(['1', '3', '7']);
  const [selectedCategory, setSelectedCategory] = useState<string>('All');

  function toggleFAQ(id: string) {
    setOpenIds(prev =>
      prev.includes(id) ? prev.filter(item => item !== id) : [...prev, id]
    );
  }

  const getCount = (catKey: string) =>
    catKey === 'All'
      ? FAQ_DATA.length
      : FAQ_DATA.filter(item => item.category === catKey).length;

  const filteredFAQs = FAQ_DATA.filter(item => {
    const matchesCategory = selectedCategory === 'All' || item.category === selectedCategory;
    const matchesSearch   = item.question.toLowerCase().includes(searchTerm.toLowerCase()) ||
                            item.answer.toLowerCase().includes(searchTerm.toLowerCase());
    return matchesCategory && matchesSearch;
  });

  return (
    <div className="app-shell">
      <Header />

      <main className="page-container">
        <section className="hero-banner" style={{ marginBottom: '2rem' }}>
          <div className="hero-badge">
            <HelpCircle size={14} />
            <span>Knowledge Base &amp; Assistance</span>
          </div>

          <h1 className="hero-title">
            Frequently Asked <span>Questions</span>
          </h1>

          <p className="hero-subtitle">
            Everything you need to know about SignalScope&apos;s two-stage forensic engine, zero-shot detection,
            false positive defenses, and privacy guarantees.
          </p>
        </section>

        {/* Search & Filter Bar */}
        <div style={{ maxWidth: '840px', margin: '0 auto 2.5rem auto' }}>
          <div className="form-group" style={{ marginBottom: '1.5rem' }}>
            <div style={{ position: 'relative' }}>
              <input
                type="text"
                id="faq-search"
                className="form-input"
                placeholder="Search questions or keywords (e.g. HDR, FLUX.1, Privacy, ELA)..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                style={{ width: '100%', paddingLeft: '2.5rem' }}
              />
              <Search size={16} style={{ position: 'absolute', left: '0.85rem', top: '50%', transform: 'translateY(-50%)', color: 'var(--ink-muted)' }} />
            </div>
          </div>

          {/* Premium Category Pill Tabs */}
          <div className="faq-category-tabs">
            {CATEGORY_CONFIG.map(({ key, label, Icon }) => {
              const isActive = selectedCategory === key;
              const count    = getCount(key);
              return (
                <button
                  key={key}
                  id={`faq-tab-${key.toLowerCase().replace(/[^a-z0-9]/g, '-')}`}
                  onClick={() => setSelectedCategory(key)}
                  className={`faq-category-pill${isActive ? ' active' : ''}`}
                  aria-pressed={isActive}
                >
                  <Icon size={13} className="faq-pill-icon" />
                  <span className="faq-pill-label">{label}</span>
                  <span className="faq-pill-count">{count}</span>
                </button>
              );
            })}
          </div>
        </div>

        {/* FAQ Accordion List */}
        <div className="faq-list" style={{ maxWidth: '840px', margin: '0 auto' }}>
          {filteredFAQs.length > 0 ? (
            filteredFAQs.map((item) => {
              const isOpen = openIds.includes(item.id);
              const catCfg = CATEGORY_CONFIG.find(c => c.key === item.category);
              const CatIcon = catCfg?.Icon ?? HelpCircle;
              return (
                <div key={item.id} className={`faq-item ${isOpen ? 'open' : ''}`}>
                  <button
                    className="faq-question"
                    onClick={() => toggleFAQ(item.id)}
                    aria-expanded={isOpen}
                    id={`faq-q-${item.id}`}
                  >
                    <span>{item.question}</span>
                    {isOpen ? <ChevronUp size={18} /> : <ChevronDown size={18} />}
                  </button>
                  {isOpen && (
                    <div className="faq-answer" id={`faq-a-${item.id}`}>
                      <div className="faq-answer-category-badge">
                        <CatIcon size={11} />
                        <span>{item.category}</span>
                      </div>
                      <p>{item.answer}</p>
                    </div>
                  )}
                </div>
              );
            })
          ) : (
            <div style={{ textAlign: 'center', padding: '3rem', background: 'var(--surface-card)', border: '1px solid var(--border-line)' }}>
              <HelpCircle size={32} style={{ color: 'var(--ink-muted)', marginBottom: '0.75rem' }} />
              <div style={{ fontWeight: 600, color: 'var(--ink-text)' }}>No matching questions found</div>
              <div style={{ fontSize: '0.88rem', color: 'var(--ink-muted)', marginTop: '0.25rem' }}>
                Try searching for another term or selecting &quot;All&quot; categories.
              </div>
            </div>
          )}
        </div>

        {/* Contact Assistance Box */}
        <div className="callout-box" style={{ maxWidth: '840px', margin: '3rem auto', textAlign: 'center' }}>
          <div className="callout-title" style={{ justifyContent: 'center' }}>
            <Mail size={16} style={{ color: 'var(--teal-real)' }} />
            <span>Still Have Questions?</span>
          </div>
          <p className="callout-text" style={{ marginBottom: '1.25rem' }}>
            Have technical inquiries or need developer feedback for SIH 2026? Contact our team directly.
          </p>
          <Link href="/contact" className="btn-instrument" style={{ textDecoration: 'none' }}>
            <Mail size={15} />
            <span>Contact Support Team</span>
          </Link>
        </div>
      </main>

      <Footer />
    </div>
  );
}
